In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.0-rc0'

In [3]:
import numpy as np

In [4]:
np.__version__


'1.18.5'

In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


11493376/11490434 [==============================] - 8s 1us/step


In [7]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 [==============================] - 1s 386us/step - loss: 0.1125 - accuracy: 0.9654
Epoch 2/5
1875/1875 [==============================] - 1s 383us/step - loss: 0.1047 - accuracy: 0.9689
Epoch 3/5
1875/1875 [==============================] - 1s 386us/step - loss: 0.1047 - accuracy: 0.9683
Epoch 4/5
1875/1875 [==============================] - 1s 399us/step - loss: 0.1005 - accuracy: 0.9695
Epoch 5/5
1875/1875 [==============================] - 1s 378us/step - loss: 0.0971 - accuracy: 0.9702
313/313 - 0s - loss: 0.0921 - accuracy: 0.9750


[0.09205330163240433, 0.9750000238418579]

In [2]:
#import libraries
#from tensorflow.python.compiler.mlcompute import mlcompute
#mlcompute.set_mlc_device(device_name='gpu')
import tensorflow as tf
import time
from tensorflow.python.compiler.mlcompute import mlcompute
from tensorflow.python.framework.ops import disable_eager_execution
disable_eager_execution()
mlcompute.set_mlc_device(device_name='gpu') # Available options are 'cpu', 'gpu', and 'any'.
tf.config.run_functions_eagerly(False)
print(tf.executing_eagerly())

#download fashion mnist dataset
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

train_set_count = len(train_labels)
test_set_count = len(test_labels)

#setup start time
t0 = time.time()

#normalize images
train_images = train_images / 255.0
test_images = test_images / 255.0

#create ML model
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)
])

#compile ML model
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

#train ML model
model.fit(train_images, train_labels, epochs=10)

#evaluate ML model on test set
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

#setup stop time
t1 = time.time()
total_time = t1-t0

#print results
print('\n')
print(f'Training set contained {train_set_count} images')
print(f'Testing set contained {test_set_count} images')
print(f'Model achieved {test_acc:.2f} testing accuracy')
print(f'Training and testing took {total_time:.2f} seconds')

False
Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 6s 96us/sample - loss: 0.4955 - accuracy: 0.8263
Epoch 2/10
60000/60000 [==============================] - 5s 85us/sample - loss: 0.3707 - accuracy: 0.8653
Epoch 3/10
60000/60000 [==============================] - 5s 84us/sample - loss: 0.3335 - accuracy: 0.8779
Epoch 4/10
60000/60000 [==============================] - 5s 85us/sample - loss: 0.3117 - accuracy: 0.8857
Epoch 5/10
60000/60000 [==============================] - 5s 86us/sample - loss: 0.2906 - accuracy: 0.8924
Epoch 6/10
60000/60000 [==============================] - 5s 84us/sample - loss: 0.2787 - accuracy: 0.8969
Epoch 7/10
60000/60000 [==============================] - 5s 85us/sample - loss: 0.2674 - accuracy: 0.9004
Epoch 8/10
60000/60000 [==============================] - 5s 85us/sample - loss: 0.2522 - accuracy: 0.9064
Epoch 9/10
60000/60000 [==============================] - 5s 86us/sample - loss: 0.2465 - accuracy: 0.9089
Epoch 10

In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = []
sequence_length = 4
num_sequence = len(a) - sequence_length

In [5]:
for i in range(num_sequence):
    b.append(a[i:i+num_sequence])
    print(np.array(b).shape)
    print(b)


(1, 6)
[array([0, 1, 2, 3, 4, 5])]
(2, 6)
[array([0, 1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6])]
(3, 6)
[array([0, 1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]), array([2, 3, 4, 5, 6, 7])]
(4, 6)
[array([0, 1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]), array([2, 3, 4, 5, 6, 7]), array([3, 4, 5, 6, 7, 8])]
(5, 6)
[array([0, 1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]), array([2, 3, 4, 5, 6, 7]), array([3, 4, 5, 6, 7, 8]), array([4, 5, 6, 7, 8, 9])]
(6,)
[array([0, 1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]), array([2, 3, 4, 5, 6, 7]), array([3, 4, 5, 6, 7, 8]), array([4, 5, 6, 7, 8, 9]), array([5, 6, 7, 8, 9])]


In [7]:
c = np.array(b)
c.shape

(6,)

In [8]:
print(c)

[array([0, 1, 2, 3, 4, 5]) array([1, 2, 3, 4, 5, 6])
 array([2, 3, 4, 5, 6, 7]) array([3, 4, 5, 6, 7, 8])
 array([4, 5, 6, 7, 8, 9]) array([5, 6, 7, 8, 9])]
